### ISSUE TITLE
CREATE: GET endpoint for Course-Information (Major -> Courses)

### ISSUE THREAD

**Issue by IgnasPanavas** [DevDogs-UGA/Optimal-Schedule-Builder#103]
**General Endpoint Requirements**

1. Must use Spring Web annotations and syntax
2. Must have javadocs
3. Should be made in controller file of the specified micro service
4. Should return the return of an unimplemented function with an appropriate type, consider if the possible return parameter might be more than one
5. Comment out the name of the function for now and return an arbitrary value to not break the code at compile time, exception if the return type has a custom type that's not implemented yet, like Course for example. If it returns course it's ok for the code to not compile for now. 
6. The function name should be logical given what you're retrieving

**Specific Endpoint Requirements**
1. Should take a major specifier (CSCI for example), should be required
2. Return a list of course objects (assume Course.java has been implemented)

**Comment by IgnasPanavas** [comment]
I updated the expected format for all endpoints. Take a look at the changes in the Bulletin controller for what I'm looking them all to look like in the future. I'm adding time to this issue and all others to implement those changes. Thanks.

**Comment by JackHarrington3** [comment]
I just made a new pull request for this issue.
