### ISSUE TITLE
MODIFY: Add Spring Docs documentation to any 3 implemented endpoints in any micro service

### ISSUE THREAD

**Issue by IgnasPanavas** [DevDogs-UGA/Optimal-Schedule-Builder#113]
**Requirements**

1. Ensure Spring Docs is added as a dependency to the micro service you are working on
2. Use Spring Docs syntax with annotations to describe each endpoint. Include both @Operation, @ApiResponses and @Tag annotation values
3. For @ApiResponses assume 2 returns, a successful one and a generally unsuccessful because the param value given was invalid
4. For @Tag just tag it for the micro service the endpoint is for

**Comment by DogeDevYT** [comment]
obsolete issue, closing.
