### ISSUE TITLE
Create a color palette for the Optimal Schedule Builder on dark mode

### ISSUE THREAD

**Issue by yeeetmaster21** [DevDogs-UGA/Optimal-Schedule-Builder#13]
We want a visually appealing interface but some people prefer dark mode, it is your task to help us accomplish this!

Refer to [this](https://medium.com/eightshapes-llc/light-dark-9f8ea42c9081) article if you need insight regarding the design process for developing light mode for a website

Keep in mind [UGA's colors](https://www.google.com/url?sa=i&url=https%3A%2F%2Fbrand.uga.edu%2Fvisual-style%2F&psig=AOvVaw0_QmBEKrmHcbjYOl2tMGCW&ust=1726798787185000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCPiwpPf4zYgDFQAAAAAdAAAAABAE) & their respective HEX codes - brand alignment is crucial

OR If you want to design a similar look as the DevDogs brand, refer to [these guidelines](https://justinquinnb.atlassian.net/wiki/external/OGU2ODkzMDE4NjhiNDA3MWE4NmNjYTgyZWVlMWFkM2Y)

Add your design to our collaborative figma file [here](https://www.figma.com/design/ZoW3A9CHTfJfw8qh7iU41b/Optimal-Schedule-Builder?m=auto&t=IrMjnD2WYJ5h0tXd-1)! (Create a new page for your respective task & name it accordingly)

**Comment by furballpillow** [comment]
![Image](https://github.com/user-attachments/assets/34361ec9-3fdc-4355-9ca8-bed33d1dfc92)
