### ISSUE TITLE
Write the generate_distance_matrix.py Python Script

### ISSUE THREAD

**Issue by Aahil52** [DevDogs-UGA/Optimal-Schedule-Builder#137]
The Python script `generate_distance_matrix.py` should generate a JSON file called `distance_matrix.json` containing a distance matrix for the buildings in `buildings.json` using the Euclidean distance formula. The output should follow the format specified in algorithm-prototyping/resources/README.md.

```json
{
  "buildings": [
    "Park Hall",
    ...
  ],
  "distance_matrix": [
    [0, ...],
    ...
  ]
}
```

**Comment by SFNDude123502** [comment]
It wont let me comment the .py file, so here is a link to it: [github.com/SFNDude123502/devDogsContributions/blob/main/generate_distance_matrix.py](url)

**Comment by SFNDude123502** [comment]
NVM, I just forked the dev branch and submitted a pull request with the code in here

**Comment by Aahil52** [comment]
Perfect, thank you. Always open a pull request from a forked repository for any code contributions. Also, for future reference, you should not be closing any issues, only setting the status to "Ready for Review".
