### ISSUE TITLE
Create Responsive HomePage NavBar & Schedule Builder NavBar

### ISSUE THREAD

**Issue by KelseySt** [DevDogs-UGA/Optimal-Schedule-Builder#175]
Create a general NavBar to be used on most (if not all) pages (file is called NavBar.tsx). The NavBar should collapse to hamburger on mobile viewports using tailwind css. Should link to the correct pages (there is a Link React Component you should use, check React documentation), feel free to create correct file directories with placeholder page.tsx files for pages such as "About", "Contact Us", etc.
NavBar under "Christine - Registration Interface Wireframe" and below:
<img width="488" alt="image" src="https://github.com/user-attachments/assets/8dadc520-eb66-49cf-83fe-aa69e3b1dd6c">

Then create a ScheduleViewNavBar.tsx with the same styling but different links as seen below (In Figma under "Samantha - Schedule View"):
<img width="545" alt="image" src="https://github.com/user-attachments/assets/45a66f36-618b-4418-8cf4-b6dec93b1e59">

Figma: https://www.figma.com/design/ZoW3A9CHTfJfw8qh7iU41b/Optimal-Schedule-Builder?node-id=428-2&node-type=canvas&t=JFmMrjPttPfTrCjO-0

When you make your pull request, please include screenshots/snipping tool (You can CTRL-C CTRL-V directly into GitHub textboxes) for review.

**Comment by co12468** [comment]
I've been having issues with setting up the project in vs code so I unassigned myself. Sorry for any inconvenience.
