### ISSUE TITLE
Create Footer

### ISSUE THREAD

**Issue by KelseySt** [DevDogs-UGA/Optimal-Schedule-Builder#176]
Create a responsive footer (Should stack Privacy Policy and Terms of Service on mobile viewport) and also includes linkedin and instagram links and icons. Should be created under components in a Footer.tsx file.
<img width="502" alt="image" src="https://github.com/user-attachments/assets/b32a433e-4fbc-42c4-89ea-703606043902">

Figma: https://www.figma.com/design/ZoW3A9CHTfJfw8qh7iU41b/Optimal-Schedule-Builder?node-id=428-2&node-type=canvas&t=JFmMrjPttPfTrCjO-0 

When you make your pull request, please include screenshots/snipping tool (You can CTRL-C CTRL-V directly into GitHub textboxes) for review.

**Comment by SidhantDash** [comment]
#197

**Comment by SidhantDash** [comment]
Let me know if there are any issues or suggested improvements with the footer 👍
