### ISSUE TITLE
Create Landing/Home Page

### ISSUE THREAD

**Issue by KelseySt** [DevDogs-UGA/Optimal-Schedule-Builder#177]
Do not worry about the NavBar and Footer, those will be added components later. Format the Homepage (/src/app/page.tsx) with the appropriate background colors, fonts, text sizes, icons, etc. The bottom center gray box should have a placeholder <Image /> for now. Ignore the side gray boxes for now until there is more UI design decisions on them. 

<img width="502" alt="image" src="https://github.com/user-attachments/assets/66bcc8d1-8098-47fa-9157-80b03be0b05c">

Figma (Under Christine - Registration Interface Wireframe): https://www.figma.com/design/ZoW3A9CHTfJfw8qh7iU41b/Optimal-Schedule-Builder?node-id=428-2&node-type=canvas&t=JFmMrjPttPfTrCjO-0

When you make your pull request, please include screenshots/snipping tool (You can CTRL-C CTRL-V directly into GitHub textboxes) for review.

**Comment by jayp822** [comment]
#196
