### ISSUE TITLE
Add Courses Component

### ISSUE THREAD

**Issue by KelseySt** [DevDogs-UGA/Optimal-Schedule-Builder#178]
Create this add courses component (**Don't** include the "Add Courses" black heading) under the components file directory however you see fit. The component has three different tab views by Section, Instructor, and CRN.

The buttons seen in the screenshot below can be abstracted into a Button.js file that takes text as an input parameter to then use for "Search" and "Add" buttons.

<img width="542" alt="image" src="https://github.com/user-attachments/assets/4c56d74f-5acd-415b-b884-050e2474e205">

<img width="428" alt="image" src="https://github.com/user-attachments/assets/977e9345-40a0-4452-b6be-bb8378ce93f4">

Mobile formatting is not yet designed, so use your best judgement for now. **Dropdown will be a separate component, so just put a placeholder until it is complete (or do it as well!)**

Figma (Under "Haley - Course Filtering + Conflict..."): https://www.figma.com/design/ZoW3A9CHTfJfw8qh7iU41b/Optimal-Schedule-Builder?node-id=347-2&node-type=canvas&t=JFmMrjPttPfTrCjO-0

When you make your pull request, please include screenshots/snipping tool (You can CTRL-C CTRL-V directly into GitHub textboxes) for review.

**Comment by lunarsceals** [comment]
#192
