### ISSUE TITLE
Filters Component

### ISSUE THREAD

**Issue by KelseySt** [DevDogs-UGA/Optimal-Schedule-Builder#180]
Implement the filter section as seen below (Including the black text header this time since it's in the box, under Filters.js or something similar in components directory). Should have usable selections and multiselect and seen below, business logic/implementation will be created later when data is live. Consider grid column layout to keep even spacing.

<img width="547" alt="image" src="https://github.com/user-attachments/assets/e569f7c6-4b0f-48b8-9a76-384bc2e4b19d">

Figma ("Haley - Course Filtering..."): https://www.figma.com/design/ZoW3A9CHTfJfw8qh7iU41b/Optimal-Schedule-Builder?node-id=347-2&node-type=canvas&t=jQmHo2fUpwoBUgtE-0

When you make your pull request, please include screenshots/snipping tool (You can CTRL-C CTRL-V directly into GitHub textboxes) for review.

**Comment by KelseySt** [comment]
I would also like the drop downs to have a little more rounded corners, such has seen here:
<img width="211" alt="image" src="https://github.com/user-attachments/assets/f38771fc-d314-4477-bd19-cfc72fa53c71">

**Comment by Extorial** [comment]
The dropdowns for the Filters Component?

**Comment by KelseySt** [comment]
Sounds good 😎
