### ISSUE TITLE
Create Professor class

### ISSUE THREAD

**Issue by Jeffrey-000** [DevDogs-UGA/Optimal-Schedule-Builder#21]
- create an object to hold professor data
- things to hold:
    -name
    -overall quality
    -would take again rating
    -difficulty rating
    -rating distributions
    -n most recent  comments
    -tags
    -anything else that i missed but would be important
-good documentation

**Comment by YuvalDeshe** [comment]
[Professor.zip](https://github.com/user-attachments/files/17157577/Professor.zip)
If having a comment for each variable is excessive, let me know so I can remove them and not add them in the future.
