### ISSUE TITLE
Reusable Card element

### ISSUE THREAD

**Issue by mykalbayouk** [DevDogs-UGA/Optimal-Schedule-Builder#210]
![CardLink](https://github.com/user-attachments/assets/280b1994-c916-422f-9034-be5a6eee2192)

Like have a spot for text to be placed, an image in the middle and text describing that image, Relatively similar to the picture above but try to stick to the devdogs color scheme. 

<img width="891" alt="Screenshot 2024-10-21 at 6 16 25 PM" src="https://github.com/user-attachments/assets/f53aafaf-201d-4b88-95de-1d4f4f0b71b2">

**Comment by SidhantDash** [comment]
<img width="374" alt="Xnip2024-10-28_18-42-02" src="https://github.com/user-attachments/assets/9b02713c-1564-46a2-82a8-81ee22bdce59">
#269
