### ISSUE TITLE
Move configs to one file

### ISSUE THREAD

**Issue by cooperbocko** [DevDogs-UGA/Optimal-Schedule-Builder#215]
Please move and delete the old config files and put them all in the course information app file.

**Comment by BryantMonahan** [comment]
Building building1 = new Building(2438, "CAGTECH", "F - 6");
buildingRepository.add(building1);

Building building2 = new Building(46, "Caldwell Hall", "C - 1");
buildingRepository.add(building2);

Building building3 = new Building(2118, "Campus Mail/Environmental Safety", "E - 6");
buildingRepository.add(building3);

Building building4 = new Building(1637, "Campus Transit Facility", "D - 8");
buildingRepository.add(building4);

Building building5 = new Building(31, "Candler Hall", "C - 1");
buildingRepository.add(building5);

Building building6 = new Building(1110, "Carlton Street Deck", "B - 4");
buildingRepository.add(building6);

Building building7 = new Building(2419, "CCRC", "E - 7");
buildingRepository.add(building7);

Building building8 = new Building(2127, "Center for Applied Isotope Study", "E - 6");
buildingRepository.add(building8);

Building building9 = new Building(2395, "Center for Molecular Medicine", "E - 7");
buildingRepository.add(building9);

Building building10 = new Building(178, "Central Campus Mech. Building", "C - 2");
buildingRepository.add(building10);
