### ISSUE TITLE
Create Schedule View Page

### ISSUE THREAD

**Issue by mykalbayouk** [DevDogs-UGA/Optimal-Schedule-Builder#235]
<img width="573" alt="Screenshot 2024-10-23 at 8 41 47 PM" src="https://github.com/user-attachments/assets/fd76cfa4-086c-40ab-bc7f-ec572c2df1de">

Should include 4 columns for each day, with their being a time shown in subsections. Class sections will occupy each block in time column, should be able to work with dummy data. 

----Not required but would be nice----
Mobile View: Perhaps have a way you can slide between each day of the week, kind of like a carousel widget so when I swipe left or right it'll take me to either the next or previous way depending on which way I swipe.

**Comment by mykalbayouk** [comment]
If multiple people want to work on this together please do since its kind of a big task, coordinate with each other and me the work ya'll do in order for points to be given adequately.

**Comment by jayp822** [comment]
This should help to do the mobile view swipe animation https://www.youtube.com/watch?v=YBkvuXpc_wo&ab_channel=Steve%28Builder.io%29

**Comment by jayp822** [comment]
#251
