### ISSUE TITLE
Form Component for Questionnaire Page 

### ISSUE THREAD

**Issue by mykalbayouk** [DevDogs-UGA/Optimal-Schedule-Builder#236]
<img width="742" alt="Screenshot 2024-10-23 at 8 48 13 PM" src="https://github.com/user-attachments/assets/733f7779-e4cf-4115-b81a-5e8a81a6c549">

The Font/Color scheme should match the DevDogs theme used before but a component housing these items is whats most important. In the example there is the ability to select from a list of options so if we could implement that, should just need to gather a txt file of like majors offered by UGA and use that for autofill. Similarly for the other form options,

**Comment by adogins** [comment]
I removed my assignment because I no longer have the time to finish this.
