### ISSUE TITLE
Create Distance/Time Gap Page

### ISSUE THREAD

**Issue by mykalbayouk** [DevDogs-UGA/Optimal-Schedule-Builder#237]
@ @
<img width="364" alt="Screenshot 2024-10-23 at 8 51 15 PM" src="https://github.com/user-attachments/assets/2b4be1b5-710a-4034-81b8-48403090080b">

For now, just create the buttons and a location for the map to sit. Until we have an exact idea of how this should work don't worry about gathering an API for the map part, as long as there is a container for it to go in once we know that should be fine.

**Comment by jayp822** [comment]
for this I think it would be a good idea to use Mapbox instead of Google Maps API since Mapbox gives a generous free tier https://www.mapbox.com/pricing""
