### ISSUE TITLE
CP-SAT 7: Comparing CP-SAT to Genetic Algorithms for Course Schedule Optimization

### ISSUE THREAD

**Issue by Aahil52** [DevDogs-UGA/Optimal-Schedule-Builder#27]
How do CP-SAT and Genetic Algorithms (GAs) compare in terms of performance, scalability, solution quality, and ease of implementation for course schedule optimization? Investigate key differences in how each approach handles hard and soft constraints, their ability to find optimal solutions, and their respective strengths and weaknesses.

Please follow these instructions carefully:
 
* Document all findings on the corresponding page in the **shared google doc** titled [CP-SAT for Course Schedule Optimization](https://docs.google.com/document/d/1NI4cuPEJdkZRDTtLI-Bz_bxfCpsmND3YbRSOPs8uke4/edit?usp=sharing).
* Keep the document **well-organized** so it can be used for future reference.
* Include **reliable sources** where necessary, including website articles, YouTube videos, research papers, and technical documentation. ChatGPT is an incredible resource, but make sure to back up its claims.
* Remember, **thorough research** ensures that we make well-informed decisions as we move forward.

**Comment by thespcrewroy** [comment]
Took me 45 minutes
