### ISSUE TITLE
Design Database for Rate My Professor

### ISSUE THREAD

**Issue by cooperbocko** [DevDogs-UGA/Optimal-Schedule-Builder#28]
A team of up to four people will design the database tables and the relationships between them for the Rate My Professor database. Please maintain a document of your contributions for points. 

Be sure to maintain proper naming conventions when creating the tables.

Also, do not close the ticket on your own, mark it as ready for review.

**Comment by Ig0rGon** [comment]
Would this database include a 'Courses' entity?

**Comment by cooperbocko** [comment]
Whatever you think is necessary. We will decide later what we do and do not need so for now you can add it.

**Comment by Ig0rGon** [comment]
![RateMyProfessor drawio](https://github.com/user-attachments/assets/7d13089f-fd92-401f-8f36-33908b2fa084)

Check this out, and lmk about it.

**Comment by cooperbocko** [comment]
Could you do it in the google draw file so it is readily available and in the same format as well?

**Comment by Ig0rGon** [comment]
![RateMyProfessorDatabase](https://github.com/user-attachments/assets/fc5f24ef-afa5-4b7c-87ba-a70c9768dbc7)

How's this one?

**Comment by Ig0rGon** [comment]
[RateMyProfessorDatabase.pdf](https://github.com/user-attachments/files/17140881/RateMyProfessorDatabase.pdf)

How's this one?

**Comment by Ig0rGon** [comment]
Here is the file for it:

![RateMyProfessorDatabase](https://github.com/user-attachments/assets/a073edf2-c67f-4a7d-bd6f-ab9d19f81534)

**Comment by ishaanchitre12** [comment]
Created a rough design of the Professor, Review, and Course tables for the Rate My Professor database. Yet to include more complex relationships.

**Comment by ishaanchitre12** [comment]
sorry, accidentally closed issue

**Comment by ishaanchitre12** [comment]
created additional department table in RMP database and formed several one-to-many relationships

**Comment by nickstoni** [comment]
[Design Database for Rate My Professor.pdf](https://github.com/user-attachments/files/17181340/Design.Database.for.Rate.My.Professor.pdf)
Please let me know if you need it in another format or by using another application.

**Comment by nickstoni** [comment]
Sorry, I accidentally closed the issue, but it is now set to "Ready for Review."

**Comment by cooperbocko** [comment]
This looks great so far! Could you do it in the google draw file so that it can be seen by everyone and edited by other people? https://docs.google.com/drawings/d/1LibWQxkO7TgwMY0GElahWZwgi-vY2eCZxD1nApIZVyk/edit

I appreciate you creating it in a class diagram, but I would like to see more of a table design that includes the foreign keys to other tables as well as intermediary tables between them. I think that style will translate better to actual code and not confuse anyone that isn't familiar with this style.

**Comment by nickstoni** [comment]
Transferred the design to Google Draw. Also, I included a written table format at the bottom.

**Comment by cooperbocko** [comment]
For the many to many relationships, could you add intermediary tables since we will needs those for the db. Also if you wanna paste it here https://docs.google.com/drawings/d/1LibWQxkO7TgwMY0GElahWZwgi-vY2eCZxD1nApIZVyk/edit

**Comment by nickstoni** [comment]
Updated the RMP Database to include additional intermediary tables. Also copied the database to the link. https://docs.google.com/drawings/d/1LibWQxkO7TgwMY0GElahWZwgi-vY2eCZxD1nApIZVyk/edit
