### ISSUE TITLE
Page to Hold Past Credits Items

### ISSUE THREAD

**Issue by mykalbayouk** [DevDogs-UGA/Optimal-Schedule-Builder#312]
<img width="625" alt="Screenshot 2024-11-04 at 6 23 53 PM" src="https://github.com/user-attachments/assets/4a1a9771-f726-4d26-a47c-91267bba58a3">

Page to Hold Past Credit Components, 2/3 already exist and the Recommended courses is a current task.

**Comment by mykalbayouk** [comment]
#311 is the reco course issue

**Comment by garrett-plumlee** [comment]
The second component "Courses Display" and third component "Recommended Courses" remain incomplete. I've made the page and it currently holds the "Past Credit" component, but this issue will remain on hold until the other two are complete.
