### ISSUE TITLE
Add/Drop Notifications

### ISSUE THREAD

**Issue by yeeetmaster21** [DevDogs-UGA/Optimal-Schedule-Builder#43]
Design a notification system and notification banner across multiple devices for students when spaces become available in courses they’re interested in.

Add your design to our collaborative figma file [here](https://www.figma.com/design/ZoW3A9CHTfJfw8qh7iU41b/Optimal-Schedule-Builder?m=auto&t=IrMjnD2WYJ5h0tXd-1)! (Create a new page for your respective task & name it accordingly)

**Comment by yeeetmaster21** [comment]
how's the progress with this design?

**Comment by nsungd** [comment]
I'm pretty much finished unless you see any issues with it
