### ISSUE TITLE
 Built-in Groupchat Interface

### ISSUE THREAD

**Issue by yeeetmaster21** [DevDogs-UGA/Optimal-Schedule-Builder#52]
Create a GroupMe like functionality & interface where you and other students added in the same class are automatically added into a group chat, an anonymous option

Another member also suggested for an option to be added into classes with your friends
Take these ideas with a grain of salt and design to what you think would logistically work best, we can always discuss more during our dev sessions too! 

Add your design to our collaborative figma file [here](https://www.figma.com/design/ZoW3A9CHTfJfw8qh7iU41b/Optimal-Schedule-Builder?m=auto&t=IrMjnD2WYJ5h0tXd-1)! (Create a new page for your respective task & name it accordingly)

**Comment by justinquinnb** [comment]
@yeeetmaster21 this requires functionality beyond the focus of the MVP and outside of resources we currently have
