### ISSUE TITLE
Create GET endpoint for aggregate professor difficulty rating for RMP

### ISSUE THREAD

**Issue by IgnasPanavas** [DevDogs-UGA/Optimal-Schedule-Builder#58]
This is a quick issue where you need to implement a GetMapping using Spring Web.

**Notes**

1. Take a parameter professorName (required) for which the difficulty rating will be returned. Do this with a parameter.
2. Also take a className parameter (optional) for which the rating might be filtered by. 
3. Make the get mapping to some logical name like "difficulty-rating" or something
4. Make sure to include java docs for your endpoint, everyone needs to understand what its used for
5. For now, since business logic has not be implemented, please put a fictitious method name in the return statement, commented out, and then actually return an arbitrary double value. Once the function is implemented we can uncomment it and use it.

For any questions just start a discussion on this issue.

**Comment by DogeDevYT** [comment]
obsolete issue, closing
