### ISSUE TITLE
Design Optimal Schedule Builder Database

### ISSUE THREAD

**Issue by cooperbocko** [DevDogs-UGA/Optimal-Schedule-Builder#75]
You will design the database for the actual schedule builder database here:
https://docs.google.com/drawings/d/1kpDOKrq-BiyGTbaMRGIDN-iHFyL1aZRFl5Dxy35cTiw/edit

Please reference the other database designs and if you have any questions please feel free to reach out!

**Comment by sebswU** [comment]
Hey, I'm just starting to learn JPA and create the design after finishing a bunch of classwork assignments. Would it be ok if you give a few pointers on what you would like to look for in the OSB database?

**Comment by cooperbocko** [comment]
for now we probably won't be working on it until the MVP is done. But once we need to start persisting data for users then we will work on it.

**Comment by cooperbocko** [comment]
obsolete
